[project]
name = "demo-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.5.1",
    "gradio[mcp]>=5.31.0",
    "openai>=1.82.0",
    "textblob>=0.19.0",
]
